services:
  gorm-demo:
    build:
      context: ./gorm-demo
    # restart: on-failure
    ports:
      - "8081:8080"
    environment:
      - POSTGRES_DSN=postgres://postgres:admin@postgres:5432/demo?sslmode=disable
    depends_on:
      - postgres
  pgx-demo:
    build:
      context: ./pgx-demo
    # restart: on-failure
    ports:
      - "8082:8080"
    environment:
      - POSTGRES_DSN=postgres://postgres:admin@postgres:5432/demo?sslmode=disable
    depends_on:
      - postgres
  sqlc-demo:
    build:
      context: ./sqlc-demo
    # restart: on-failure
    ports:
      - "8083:8080"
    environment:
      - POSTGRES_DSN=postgres://postgres:admin@postgres:5432/demo?sslmode=disable
    depends_on:
      - postgres
  sqlx-demo:
    build:
      context: ./sqlx-demo
    # restart: on-failure
    ports:
      - "8084:8080"
    environment:
      - POSTGRES_DSN=postgres://postgres:admin@postgres:5432/demo?sslmode=disable
    depends_on:
      - postgres
  squirrel-demo:
    build:
      context: ./squirrel-demo
    # restart: on-failure
    ports:
      - "8085:8080"
    environment:
      - POSTGRES_DSN=postgres://postgres:admin@postgres:5432/demo?sslmode=disable
    depends_on:
      - postgres
  ent-demo:
    build:
      context: ./ent-demo
    # restart: on-failure
    ports:
      - "8086:8080"
    environment:
      - POSTGRES_DSN=postgres://postgres:admin@postgres:5432/demo?sslmode=disable
    depends_on:
      - postgres
  bun-demo:
    build:
      context: ./bun-demo
    # restart: on-failure
    ports:
      - "8087:8080"
    environment:
      - POSTGRES_DSN=postgres://postgres:admin@postgres:5432/demo?sslmode=disable
    depends_on:
      - postgres
  postgres:
    container_name: postgres
    image: postgres:14
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=demo
    ports:
      - "5432:5432"
    volumes:
      - postgres:/var/lib/postgresql/data
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4_container
    restart: always
    ports:
      - "8888:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
    volumes:
      - pgadmin-data:/var/lib/pgadmin
      - ./pgadmin/servers.json:/pgadmin4/servers.json
    depends_on:
      - postgres
volumes:
  postgres:
  pgadmin-data:
